### ISSUE TITLE
Different number of results between staging and production

### ISSUE THREAD

**Issue by ppolischuk** [CrossRef/cr-search#26]
http://search-staging.crossref.org/?q=Palmer+ontologies+publishing
140,247 in production
137,419 in staging

http://search-staging.crossref.org/?q=galaxy+classification
243,447 in production
243,024 in staging

http://search-staging.crossref.org/?q=RSG-09-276-01-CSM
995,895 in production
815,089 in staging

**Comment by gbilder** [comment]
These are likely due to a deliberate change we made in the way in which CRMDS does queries.

In the past, when the only metadata that CRMDS indexed was bibliographic, CRMDS was very good at locating the most relevant record if you just had a partial bibliographic entry.

But as we've added other metadata, CRMDS has gotten worse at surfacing the correct record when given a partial reference. In the API we fixed this by adding a new `query.bibliographic` parameter. When we revised CRMDS, we decided to use this (instead of plain `query`) because it would *restore* CRMDS to behaving the way it did before we started adding so much non-descriptive metadata.

**Comment by ppolischuk** [comment]
No longer seeing a discrepancy between staging and production in the number of results returned for these queries. Closing.

**Comment by gbilder** [comment]
So Again, in the example given, searching for`Palmer ontologies publishing`, current production returns ~109K results. Staging returns ~106k results. This is consistent with the difference between searching REST API using `query` (current production) and `query.bibliographic` (staging). See examples :

http://api.crossref.org/works?query=Palmer%20ontologies%20publishing&facet=type-name:*

http://api.crossref.org/works?query.bibliographic=Palmer%20ontologies%20publishing&facet=type-name:*

Given that CRMDS is largely used for bibliographic lookup and resolving references, this change actually returns CRMDS to the way in which it *used* to work prior to our including so much non-bibliographic metadata in our records.
